Oops! Assertion failed

The following assertion was not satisfied
  assert 1 << 3 is False, error()

Assertion values
  assert 1 << 3 is False, error()
           ^ is = 8
  assert 1 << 3 is False, error()
                ^ is = False
  assert 1 << 3 is False, error()
  ^ is False

Where
  File 'tests/tests.py', line 204 in 'run'

196|                      with raises(AssertionError) as e:
197|                          assert 1 ** 3 is False, error()
198|                      test.note(e.exception)
199|                      with this() as that:
200|                          assert that(snapshot(e.exception, "binary-ops-pow", encoder=str)), error()
201|  
202|                  with subsuite.test("lshift") as test:
203|                      with raises(AssertionError) as e:
204|>                         assert 1 << 3 is False, error()
205|                      test.note(e.exception)
206|                      with this() as that:
207|                          assert that(snapshot(e.exception, "binary-ops-lshift", encoder=str)), error()
