Oops! Assertion failed

The following assertion was not satisfied
  assert ~4 is False, error()

Assertion values
  assert ~4 is False, error()
         ^ is = -5
  assert ~4 is False, error()
            ^ is = False
  assert ~4 is False, error()
  ^ is False

Where
  File 'tests/tests.py', line 254 in 'run'

246|                          assert 1 + 3 - 4 * 5 ** 1 >> 1 << 3 % 5 | 2 ^ 5 & 6 // 3 is False, error()
247|                      test.note(e.exception)
248|                      with this() as that:
249|                          assert that(snapshot(e.exception, "binary-ops-mixed-ops", encoder=str)), error()
250|  
251|              with suite.test("unary ops") as subsuite:
252|                  with subsuite.test("invert") as test:
253|                      with raises(AssertionError) as e:
254|>                         assert ~4 is False, error()
255|                      test.note(e.exception)
256|                      with this() as that:
257|                          assert that(snapshot(e.exception, "unary-ops-invert", encoder=str)), error()
