Oops! Assertion failed

The following assertion was not satisfied
  assert object() is False, error()

Assertion values
  assert object() is False, error()
         ^ is = <object object at 0x7fc4d566c1b0>
  assert object() is False, error()
                  ^ is = False
  assert object() is False, error()
  ^ is False

Where
  File 'tests/tests.py', line 389 in 'run'

381|                      with raises(AssertionError) as e:
382|                          assert object is False, error()
383|                      test.note(e.exception)
384|                      with this() as that:
385|                          assert that(snapshot(e.exception, "common-types-object-type", encoder=str)), error()
386|                  
387|                  with subsuite.test("object") as test:
388|                      with raises(AssertionError) as e:
389|>                         assert object() is False, error()
390|                      test.note(e.exception)
391|                      with this() as that:
392|                          assert that(snapshot(e.exception, "common-types-object", encoder=str)), error()
